fileverse/fileverse-ddoc

- package-lock.json
- package.json
- src/packages/ddoc/extensions/d-block/dblock.ts
- src/packages/ddoc/extensions/default-extension.ts
- src/packages/ddoc/use-ddoc-editor.tsx
> feat: Update tiptap-markdown and fix crash when pasting large texts

- package-lock.json
- package.json
- package/ddoc-editor.tsx
- vite.config.ts
- Updated `fileverse/ui` package to `4.0.6`
- Updated Vite Build Config to build just the ES module
- fixed editor content padding on mobile screen
- fixed navbar width on mobile and tablet screens
> updated fileverse/ui package, build config and mobile screen UI fixes

- package-lock.json
- package.json
- package/extensions/mardown-paste-handler/index.ts
- Update markdown table export
> feat: update markdown table export

- package/components/editor-toolbar.tsx
- package/components/editor-utils.tsx
- package/extensions/mardown-paste-handler/index.ts
- Dynamic Modal for exporting MD
> feat: export markdown ux modal

- package-lock.json
- package.json
- package/extensions/mardown-paste-handler/index.ts
> md: bullet list bug

- .vscode/settings.json
- package-lock.json
- package.json
- package/common/toolbar-button.tsx
- package/components/editor-bubble-menu.tsx
- package/components/editor-toolbar.tsx
- package/components/editor-utils.tsx
- package/components/node-selector.tsx
- Update dropdowns for utils for better UX
- Refactor
> feat: refactor and update dropdown for utils

- package.json
- package/components/editor-bubble-menu.tsx
- package/components/editor-utils.tsx
- package/components/slash-comand.tsx
- package/extensions/action-button/action-button-node-view.tsx
- package/extensions/d-block/dblock-node-view.tsx
- package/extensions/default-extension.ts
- package/extensions/multi-column/columns.ts
- package/extensions/supercharged-table/extension-table-cell/table-cell-node-view.tsx
- package/utils/template-utils.tsx
> feat: update templates

- demo/package-lock.json
- demo/src/App.tsx
- package-lock.json
- package.json
- package/components/editor-toolbar.tsx
- package/components/editor-utils.tsx
- package/ddoc-editor.tsx
> feat: integrate toast and fix toolbar layout

- package/extensions/d-block/dblock.ts
https://fileverse.slack.com/archives/C04G9DMHX47/p1727430912732739?thread_ts=1727426009.860899&cid=C04G9DMHX47
> fixed entering issues

- package/components/editor-bubble-menu.tsx
- package/components/editor-utils.tsx
- package/components/mobile-toolbar.tsx
- package/ddoc-editor.tsx
- package/extensions/d-block/dblock-node-view.tsx
- package/extensions/default-extension.ts
- package/extensions/resizable-media/media-paste-drop-plugin/media-paste-drop-plugin.ts
- package/extensions/resizable-media/resizable-media-node-view.tsx
- package/extensions/resizable-media/resizable-media.ts
- Fixed link's edge case on rendering twitter url (between post and username page)
- Fixed link popup (both Toolbar and Bubble menu) to work with url containing @ symbols + prompt error toast when invalid
- Fixed Cmd+K Link Popup to work properly as the inline popups
- Fixed clipboard copied image not prompting when exceeding size limit (now working with Copy Image and Copy Image Address)
> fix: all link problems + add error toast for copy image

- package/extensions/d-block/dblock.ts
- finally complete list logic on Enter
> revert code enter logic & complete list logic

- demo/src/App.tsx
- package/components/tag-input.tsx
- package/ddoc-editor.tsx
- package/types.ts
> added tag feature

- package-lock.json
- package.json
- package/ddoc-editor.tsx
- package/types.ts
- Get TagInput from fileverse/ui
- Added selectedTags and setSelectedTags
> update selected tags and taginput

- package/extensions/default-extension.ts
- package/extensions/resizable-media/media-paste-drop-plugin/media-paste-drop-plugin.ts
- package/extensions/resizable-media/resizable-media.ts
- package/use-ddoc-editor.tsx
- package/utils/upload-images.tsx
- Refix error toast for image upload (tested )
> refix error toast for image upload

- package-lock.json
- package.json
- package/ddoc-editor.tsx
- package/extensions/resizable-media/resizable-media.ts
> update tags design

- package/extensions/mardown-paste-handler/index.ts
- remove extra br of list items
- add new input rule for markdown styled link
> feat: remove extra br of list items

- package/extensions/mardown-paste-handler/index.ts
- package/hooks/use-content-item-actions.tsx
[The Surge.md](https://github.com/user-attachments/files/17459583/The.Surge.md)
> bugfix: export lists in table md

- package/extensions/d-block/dblock.ts
https://jam.dev/c/674c8a05-928b-404c-90f7-5b163911d2d0
> bugfix: nested list item backspace bug

- package/ddoc-editor.tsx
Reverts fileverse/fileverse-ddoc#140
> Revert "bugfix: scrolling issue"

- package/components/editor-bubble-menu.tsx
- package/components/editor-utils.tsx
This includes the following fixes-
- Incorrect drop-shadow fro floating tollbar
- Incorrect top, bottom, left and right paddings 
- Missed border for floating toolbar
- Incorrect order of tools, tools not grouped
- Border 2px
- Incorrect font-weight
- Incorrect min-height
> fix: Design changes

- package/styles/editor.scss
- package/utils/md-to-html.ts
https://linear.app/fileverse/issue/DDO-130
> bugfix: image cut off in slides

- package/utils/handle-print.ts
https://linear.app/fileverse/issue/ENG-609
> bugfix: pdf print handling vertical image

- package/utils/md-to-html.ts
https://linear.app/fileverse/issue/ENG-610
> bugfix: initial hyperlinks of lists not showing on slides

- package-lock.json
- package.json
- package/components/editor-utils.tsx
- package/components/mobile-toolbar.tsx
- package/components/utils-modal.tsx
- remove hover state from Tool Buttons on mobile screens
- Text Formatting Popup not opening on one click
- Editor being focused when clicking on Text Formatting Options
- Disable auto zoom in Link Popup on mobile
> multiple mobile fixes

- package/extensions/d-block/dblock.ts
https://fileverse.slack.com/archives/C04G9DMHX47/p1737029447695869
> fixed backspace bug

- package/utils/handle-print.ts
https://linear.app/fileverse/issue/TEC-61/add-page-break-support-for-editor-pdf-export
> added page break support for editor pdf export

- package/components/presentation-mode/presentation-mode.tsx
- package/styles/editor.scss
> css updates

- package/components/editor-bubble-menu/node-selector.tsx
- package/components/editor-utils.tsx
- package/components/presentation-mode/preview-panel.tsx
- package/extensions/d-block/dblock.ts
- package/extensions/default-extension.ts
- package/extensions/resizable-media/resizable-media-node-view.tsx
- package/styles/editor.scss
https://linear.app/fileverse/issue/TEC-222/improvements-on-core-editors-parent-ticket-ddoc-prod-errors
> Editor Improvements

- package/components/editor-utils.tsx
- package/styles/fonts.css
- package/styles/index.css
> chore: add more fonts
